
CREATE TABLE [dbo].[SSASConnectionLog](
	[CONNECTION_ID] [INT] NULL,
	[CONNECTION_USER_NAME] [NVARCHAR](255) NULL,
	[CONNECTION_IMPERSONATED_USER_NAME] [NVARCHAR](255) NULL,
	[CONNECTION_HOST_NAME] [NVARCHAR](255) NULL,
	[CONNECTION_HOST_APPLICATION] [NVARCHAR](255) NULL,
	[CONNECTION_START_TIME] [DATETIME] NULL,
	[CONNECTION_ELAPSED_TIME_MS] [BIGINT] NULL,
	[CONNECTION_LAST_COMMAND_START_TIME] [DATETIME] NULL,
	[CONNECTION_LAST_COMMAND_END_TIME] [DATETIME] NULL,
	[CONNECTION_LAST_COMMAND_ELAPSED_TIME_MS] [BIGINT] NULL,
	[CONNECTION_IDLE_TIME_MS] [BIGINT] NULL,
	[CONNECTION_BYTES_SENT] [BIGINT] NULL,
	[CONNECTION_DATA_BYTES_SENT] [BIGINT] NULL,
	[CONNECTION_BYTES_RECEIVED] [BIGINT] NULL,
	[CONNECTION_DATA_BYTES_RECEIVED] [BIGINT] NULL,
	[DiscoveryTime] [DATETIME] NULL
) 
