USE [Test]

CREATE TABLE [dbo].[SSASSessionLog](
	[SESSION_ID] [NVARCHAR](255) NULL,
	[SESSION_SPID] [INT] NULL,
	[SESSION_CONNECTION_ID] [INT] NULL,
	[SESSION_USER_NAME] [NVARCHAR](255) NULL,
	[SESSION_CURRENT_DATABASE] [NVARCHAR](255) NULL,
	[SESSION_USED_MEMORY] [INT] NULL,
	[SESSION_PROPERTIES] [NVARCHAR](255) NULL,
	[SESSION_START_TIME] [DATETIME] NULL,
	[SESSION_ELAPSED_TIME_MS] [NUMERIC](20, 0) NULL,
	[SESSION_LAST_COMMAND_START_TIME] [DATETIME] NULL,
	[SESSION_LAST_COMMAND_END_TIME] [DATETIME] NULL,
	[SESSION_LAST_COMMAND_ELAPSED_TIME_MS] [NUMERIC](20, 0) NULL,
	[SESSION_IDLE_TIME_MS] [NUMERIC](20, 0) NULL,
	[SESSION_CPU_TIME_MS] [NUMERIC](20, 0) NULL,
	[SESSION_LAST_COMMAND_CPU_TIME_MS] [NUMERIC](20, 0) NULL,
	[SESSION_STATUS] [INT] NULL,
	[SESSION_READS] [NUMERIC](20, 0) NULL,
	[SESSION_WRITES] [NUMERIC](20, 0) NULL,
	[SESSION_READ_KB] [NUMERIC](20, 0) NULL,
	[SESSION_WRITE_KB] [NUMERIC](20, 0) NULL,
	[SESSION_COMMAND_COUNT] [INT] NULL,
	[DiscoveryTime] [DATETIME] NULL
) 
